/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,css}', './components/**/*.{js,ts,jsx,tsx,css}'],
  darkMode: 'class', // or 'media' or 'class' or false
  prefix: '',
  theme: {
    extend: {
      fontSize: {
        '3xs': '0.5rem',
        '2xs': '0.625rem',
      },
      spacing: {
        4.5: '1.125rem',
        6.5: '1.625rem',
      },
      minHeight: {
        5: '1.25rem',
      },
      minWidth: {
        5: '1.25rem',
      },
    },
    colors: {
      red: {
        DEFAULT: '#b72226',
        fail: '#c6394a',
        cinnabar: '#EB4034',
        firebrick: '#B72226',
        auburn: '#A12020',
        shimmer: '#C25555',
        'geranium-lake': '#DB2E2E',
        'tart-orange': '#F24C4C',
      },
      green: { DEFAULT: '#5cc311', success: '#1ea966', jungle: '#1E9692' },
      blue: {
        indigo: '#1f3870',
        dark: '#313c8a',
        lavender: '#CDDEFA',
        jordy: '#91B4ED',
        yonder: '#4471AD',
        royal: '#4072DE',
        'lapis-lazuli': '#33689E',
        'light-sky': '#8AC0FF',
        palatinate: '#373CDB',
        pastel: '#A9BDCC',
        'purple-navy': '#4c5c8c',
        carolina: '#5697CC',
        'little-boy': '#65A6DB',
        chinese: '#404FA3',
        yinmn: '#305186',
        bleu: '#2e79de',
      },
      cyan: {
        DEFAULT: '#378a97',
        light: '#bfdcdf',
        gainsboro: '#D5E3E6',
        'medium-turquoise': '#50C8B8',
        maximum: '#36c2bd',
        platinum: '#DCE3E7',
      },
      gray: {
        DEFAULT: '#7D7D7D',
        spanish: '#9E9E9E',
        bright: '#E8ECEF',
        light: '#D4D4D4',
        silk: '#BABABA',
        cultured: '#F6F6F6',
        platinum: '#E8E8E8',
      },
      silver: {
        dark: '#6D6E6E',
        metallic: '#9DA5B0',
        sonic: '#767676',
        light: '#D8D8D8',
        chinese: '#C4CFCD',
        foil: '#B0B0B0',
      },
      pink: {
        carmine: '#E84646',
        paradise: '#E94560',
        mauvelous: '#F797A9',
        'rose-vale': '#AB5252',
        'fuzzy-wuzzy': '#C96D6D',
      },
      'african-violet': '#A883C7',
      white: { DEFAULT: '#fff', 'anti-flash': '#EDF1F3', azureish: '#DFECED', cultured: '#F5F7F8' },
      black: '#000',
      status: {
        moonstone: '#6FA8BD',
        'vegas-gold': '#C2B851',
        topaz: '#944141',
        'sea-green': '#36854D',
        'sheen-green': '#68ABA0',
        ming: '#3E7278',
        'russian-green': '#739E67',
        liberty: '#6256A6',
        sunburst: '#917234',
        purpureus: '#9356A6',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
